### ISSUE TITLE
Unrecognized EA user.DOSATTRIB - Error - SYMBOLIC_LINK is non-resident

### ISSUE THREAD

**Issue by GeorgeV220** [maharmstone/ntfs2btrfs#62]
Hello,
When I'm trying to convert my Games SSD from NTFS to BTRFS I get those errors:
https://hastebin.com/owakizevoy

**Comment by maharmstone** [comment]
Thanks. That's interesting: I do wonder what it is that's creating a reparse point large enough to be non-resident.

>Unrecognized EA user.DOSATTRIB

Were these files created on Linux - via the FUSE driver or the new kernel driver? You shouldn't get a user.DOSATTRIB created on Windows.

**Comment by GeorgeV220** [comment]
> Thanks. That's interesting: I do wonder what it is that's creating a reparse point large enough to be non-resident.
> 
> > Unrecognized EA user.DOSATTRIB
> 
> Were these files created on Linux - via the FUSE driver or the new kernel driver? You shouldn't get a user.DOSATTRIB created on Windows.

Thank you for your reply.
Those files were created in a Linux system (Garuda Linux) with the usage of the new Open Source Paragon driver, I want to mention that recently I had a problem with this NTFS driver and I used the chkdsk command from the windows installation media, idk if that can cause a problem.

**Comment by maharmstone** [comment]
I've encountered the same error on a fresh install of Windows 11 22H2, so it's probably not Paragon's fault. I'll look into it.

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/ntfs2btrfs/commit/95888fd403428fa38f2031bbb261aa01e99cf0c1

**Comment by VA1DER** [comment]
I am still getting "Unrecognized EA user.DOSATTRIB" message for every file.  This is, again, using the new Paragon NTFS3 driver.
